#!/usr/bin/env ruby

$:.unshift(File.join(File.dirname(__FILE__), '..', 'src/main/ruby'))

require 'database'

sqlite_file = ARGV.first || 'data/e4abdddd416c93a213c1249f3929ea3474ae38df.sqlite'

Database.new(sqlite_file) do |db|
  if db.tables.include?(:handle)
    require 'models/v2'
  else
    require 'models/v1'
  end
  require 'pry'
  binding.pry
end
