#!/usr/bin/env bash

BACKUP_DIR=~/Library/Application\ Support/MobileSync/Backup/
DATABASE_NAME="3d0d7e5fb2ce288813306e4d4636395e047a3d28"

mkdir -p data

for DIR in $(ls "$BACKUP_DIR"); do
  cp -p "$BACKUP_DIR/$DIR/$DATABASE_NAME" "data/$DIR.sqlite"
done
